// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CEUS.WorkShop.TestUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LoadTest - Use 'LoadTestParams' to pass parameters into this method.
        /// </summary>
        public void LoadTest()
        {
            #region Variable Declarations
            HtmlEdit uICuentadeusuarioEdit = this.UIIniciarsesiónenOfficWindow.UIIniciarsesiónenOfficDocument.UICuentadeusuarioEdit;
            HtmlEdit uIContraseñaEdit = this.UIIniciarsesiónenOfficWindow.UIIniciarsesiónenOfficDocument.UIContraseñaEdit;
            HtmlSpan uIIniciarsesiónPane = this.UIIniciarsesiónenOfficWindow.UIIniciarsesiónenOfficDocument.UIIniciarsesiónPane;
            HtmlDiv uIPromotedlinksbody_WPPane = this.UIIniciarsesiónenOfficWindow.UIWorkShopDevHomeDocument.UIPromotedlinksbody_WPPane;
            HtmlDiv uIIntroducciónalasapliPane = this.UIIniciarsesiónenOfficWindow.UIWorkShopDevHomeDocument.UILayoutsTableTable.UIIntroducciónalasapliPane;
            HtmlHyperlink uICEUSWokshopProviderHyperlink = this.UIIniciarsesiónenOfficWindow.UIWorkShopDevHomeDocument.UICEUSWokshopProviderHyperlink;
            HtmlHyperlink uIHomeHyperlink = this.UIIniciarsesiónenOfficWindow.UIHomePageMyASPNETApplDocument.UIHomeHyperlink;
            HtmlHyperlink uIAboutHyperlink = this.UIIniciarsesiónenOfficWindow.UIHomePageMyASPNETApplDocument1.UIAboutHyperlink;
            HtmlHyperlink uIContactHyperlink = this.UIIniciarsesiónenOfficWindow.UIAboutMyASPNETApplicaDocument.UIContactHyperlink;
            #endregion

            // Type 'adrian.diaz' in 'Cuenta de usuario' text box
            uICuentadeusuarioEdit.Text = this.LoadTestParams.UICuentadeusuarioEditText;

            // Type 'Alt, Control + 2' in 'Cuenta de usuario' text box
            Keyboard.SendKeys(uICuentadeusuarioEdit, this.LoadTestParams.UICuentadeusuarioEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'adrian.diaz@adriandiaz.onmicrosoft.com' in 'Cuenta de usuario' text box
            uICuentadeusuarioEdit.Text = this.LoadTestParams.UICuentadeusuarioEditText1;

            // Type '{Tab}' in 'Cuenta de usuario' text box
            Keyboard.SendKeys(uICuentadeusuarioEdit, this.LoadTestParams.UICuentadeusuarioEditSendKeys1, ModifierKeys.None);

            // Type '********' in 'Contraseña' text box
            uIContraseñaEdit.Password = this.LoadTestParams.UIContraseñaEditPassword;

            // Click 'Iniciar sesión' pane
            Mouse.Click(uIIniciarsesiónPane, new Point(73, 18));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'promotedlinksbody_WPQ2' pane at (1, 1)
            Mouse.Hover(uIPromotedlinksbody_WPPane, new Point(1, 1));

            // Mouse hover 'Introducción a las aplicaciones de Offic' pane at (1, 1)
            Mouse.Hover(uIIntroducciónalasapliPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'CEUS.Wokshop.Provider' link
            Mouse.Click(uICEUSWokshopProviderHyperlink, new Point(71, 5));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(38, 32));

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(39, 38));

            // Click 'Contact' link
            Mouse.Click(uIContactHyperlink, new Point(47, 29));
        }
        
        #region Properties
        public virtual LoadTestParams LoadTestParams
        {
            get
            {
                if ((this.mLoadTestParams == null))
                {
                    this.mLoadTestParams = new LoadTestParams();
                }
                return this.mLoadTestParams;
            }
        }
        
        public UIIniciarsesiónenOfficWindow UIIniciarsesiónenOfficWindow
        {
            get
            {
                if ((this.mUIIniciarsesiónenOfficWindow == null))
                {
                    this.mUIIniciarsesiónenOfficWindow = new UIIniciarsesiónenOfficWindow();
                }
                return this.mUIIniciarsesiónenOfficWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoadTestParams mLoadTestParams;
        
        private UIIniciarsesiónenOfficWindow mUIIniciarsesiónenOfficWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoadTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class LoadTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'adrian.diaz' in 'Cuenta de usuario' text box
        /// </summary>
        public string UICuentadeusuarioEditText = "adrian.diaz";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Cuenta de usuario' text box
        /// </summary>
        public string UICuentadeusuarioEditSendKeys = "2";
        
        /// <summary>
        /// Type 'adrian.diaz@adriandiaz.onmicrosoft.com' in 'Cuenta de usuario' text box
        /// </summary>
        public string UICuentadeusuarioEditText1 = "adrian.diaz@adriandiaz.onmicrosoft.com";
        
        /// <summary>
        /// Type '{Tab}' in 'Cuenta de usuario' text box
        /// </summary>
        public string UICuentadeusuarioEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Contraseña' text box
        /// </summary>
        public string UIContraseñaEditPassword = "PETcLM/PkLLhQB0IHOhYvmtEcFd87WTV";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIIniciarsesiónenOfficWindow : BrowserWindow
    {
        
        public UIIniciarsesiónenOfficWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Iniciar sesión en Office 365";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Iniciar sesión en Office 365");
            this.WindowTitles.Add("WorkShop - DevHome");
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            this.WindowTitles.Add("About - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIIniciarsesiónenOfficDocument UIIniciarsesiónenOfficDocument
        {
            get
            {
                if ((this.mUIIniciarsesiónenOfficDocument == null))
                {
                    this.mUIIniciarsesiónenOfficDocument = new UIIniciarsesiónenOfficDocument(this);
                }
                return this.mUIIniciarsesiónenOfficDocument;
            }
        }
        
        public UIWorkShopDevHomeDocument UIWorkShopDevHomeDocument
        {
            get
            {
                if ((this.mUIWorkShopDevHomeDocument == null))
                {
                    this.mUIWorkShopDevHomeDocument = new UIWorkShopDevHomeDocument(this);
                }
                return this.mUIWorkShopDevHomeDocument;
            }
        }
        
        public UIHomePageMyASPNETApplDocument UIHomePageMyASPNETApplDocument
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument == null))
                {
                    this.mUIHomePageMyASPNETApplDocument = new UIHomePageMyASPNETApplDocument(this);
                }
                return this.mUIHomePageMyASPNETApplDocument;
            }
        }
        
        public UIHomePageMyASPNETApplDocument1 UIHomePageMyASPNETApplDocument1
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument1 == null))
                {
                    this.mUIHomePageMyASPNETApplDocument1 = new UIHomePageMyASPNETApplDocument1(this);
                }
                return this.mUIHomePageMyASPNETApplDocument1;
            }
        }
        
        public UIAboutMyASPNETApplicaDocument UIAboutMyASPNETApplicaDocument
        {
            get
            {
                if ((this.mUIAboutMyASPNETApplicaDocument == null))
                {
                    this.mUIAboutMyASPNETApplicaDocument = new UIAboutMyASPNETApplicaDocument(this);
                }
                return this.mUIAboutMyASPNETApplicaDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIIniciarsesiónenOfficDocument mUIIniciarsesiónenOfficDocument;
        
        private UIWorkShopDevHomeDocument mUIWorkShopDevHomeDocument;
        
        private UIHomePageMyASPNETApplDocument mUIHomePageMyASPNETApplDocument;
        
        private UIHomePageMyASPNETApplDocument1 mUIHomePageMyASPNETApplDocument1;
        
        private UIAboutMyASPNETApplicaDocument mUIAboutMyASPNETApplicaDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIIniciarsesiónenOfficDocument : HtmlDocument
    {
        
        public UIIniciarsesiónenOfficDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Iniciar sesión en Office 365";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/login.srf";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://login.microsoftonline.com/login.srf?wa=wsignin1%2E0&rpsnv=4&ct=1433492754" +
                "&rver=6%2E1%2E6206%2E0&wp=MBI&wreply=https%3A%2F%2Fadriandiaz%2Esharepoint%2Ecom" +
                "%2F%5Fforms%2Fdefault%2Easpx%3Fapr%3D1&lc=3082&id=500046";
            this.WindowTitles.Add("Iniciar sesión en Office 365");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UICuentadeusuarioEdit
        {
            get
            {
                if ((this.mUICuentadeusuarioEdit == null))
                {
                    this.mUICuentadeusuarioEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICuentadeusuarioEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_userid_inputtext";
                    this.mUICuentadeusuarioEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUICuentadeusuarioEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Cuenta de usuario";
                    this.mUICuentadeusuarioEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICuentadeusuarioEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICuentadeusuarioEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required email field normaltext";
                    this.mUICuentadeusuarioEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" tabindex=\"1\" class=\"login_t";
                    this.mUICuentadeusuarioEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUICuentadeusuarioEdit.WindowTitles.Add("Iniciar sesión en Office 365");
                    #endregion
                }
                return this.mUICuentadeusuarioEdit;
            }
        }
        
        public HtmlEdit UIContraseñaEdit
        {
            get
            {
                if ((this.mUIContraseñaEdit == null))
                {
                    this.mUIContraseñaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIContraseñaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_password_inputtext";
                    this.mUIContraseñaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIContraseñaEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Contraseña";
                    this.mUIContraseñaEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIContraseñaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIContraseñaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required field normaltext";
                    this.mUIContraseñaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" tabindex=\"2\" class=\"login_";
                    this.mUIContraseñaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIContraseñaEdit.WindowTitles.Add("Iniciar sesión en Office 365");
                    #endregion
                }
                return this.mUIContraseñaEdit;
            }
        }
        
        public HtmlSpan UIIniciarsesiónPane
        {
            get
            {
                if ((this.mUIIniciarsesiónPane == null))
                {
                    this.mUIIniciarsesiónPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIIniciarsesiónPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cred_sign_in_button";
                    this.mUIIniciarsesiónPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIIniciarsesiónPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Iniciar sesión";
                    this.mUIIniciarsesiónPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIIniciarsesiónPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "button normaltext cred_sign_in_button refresh_domain_state";
                    this.mUIIniciarsesiónPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"11\" class=\"button normaltext cred_sign_in_button refresh_domain_state\" " +
                        "id=\"cred_sign_in_button\" role=\"button\" style=\"opacity: 1;\" onclick=\"Post.SubmitC" +
                        "reds();return false;\"";
                    this.mUIIniciarsesiónPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUIIniciarsesiónPane.WindowTitles.Add("Iniciar sesión en Office 365");
                    #endregion
                }
                return this.mUIIniciarsesiónPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUICuentadeusuarioEdit;
        
        private HtmlEdit mUIContraseñaEdit;
        
        private HtmlSpan mUIIniciarsesiónPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIWorkShopDevHomeDocument : HtmlDocument
    {
        
        public UIWorkShopDevHomeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "WorkShop - DevHome";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/sites/workshop/_layouts/15/start.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://adriandiaz.sharepoint.com/sites/workshop/_layouts/15/start.aspx#/SitePage" +
                "s/DevHome.aspx";
            this.WindowTitles.Add("WorkShop - DevHome");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIPromotedlinksbody_WPPane
        {
            get
            {
                if ((this.mUIPromotedlinksbody_WPPane == null))
                {
                    this.mUIPromotedlinksbody_WPPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIPromotedlinksbody_WPPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "promotedlinksbody_WPQ2";
                    this.mUIPromotedlinksbody_WPPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIPromotedlinksbody_WPPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Crear una aplicación\r\n\r\nUse las herramie";
                    this.mUIPromotedlinksbody_WPPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIPromotedlinksbody_WPPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-promlink-body";
                    this.mUIPromotedlinksbody_WPPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ms-promlink-body\" id=\"promotedlinksbody_WPQ2\"";
                    this.mUIPromotedlinksbody_WPPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "91";
                    this.mUIPromotedlinksbody_WPPane.WindowTitles.Add("WorkShop - DevHome");
                    #endregion
                }
                return this.mUIPromotedlinksbody_WPPane;
            }
        }
        
        public UILayoutsTableTable UILayoutsTableTable
        {
            get
            {
                if ((this.mUILayoutsTableTable == null))
                {
                    this.mUILayoutsTableTable = new UILayoutsTableTable(this);
                }
                return this.mUILayoutsTableTable;
            }
        }
        
        public HtmlHyperlink UICEUSWokshopProviderHyperlink
        {
            get
            {
                if ((this.mUICEUSWokshopProviderHyperlink == null))
                {
                    this.mUICEUSWokshopProviderHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICEUSWokshopProviderHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICEUSWokshopProviderHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = "applink";
                    this.mUICEUSWokshopProviderHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICEUSWokshopProviderHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "CEUS.Wokshop.Provider";
                    this.mUICEUSWokshopProviderHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/sites/workshop/_layouts/15/appredirect.aspx";
                    this.mUICEUSWokshopProviderHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICEUSWokshopProviderHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://adriandiaz.sharepoint.com/sites/workshop/_layouts/15/appredirect.aspx?ins" +
                        "tance_id=c632f1bd%2D626a%2D4bea%2Dadb8%2D4c28cca615f4&dev_site_list=1";
                    this.mUICEUSWokshopProviderHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICEUSWokshopProviderHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "name=\"applink\" href=\"https://adriandiaz.";
                    this.mUICEUSWokshopProviderHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "59";
                    this.mUICEUSWokshopProviderHyperlink.WindowTitles.Add("WorkShop - DevHome");
                    #endregion
                }
                return this.mUICEUSWokshopProviderHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIPromotedlinksbody_WPPane;
        
        private UILayoutsTableTable mUILayoutsTableTable;
        
        private HtmlHyperlink mUICEUSWokshopProviderHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILayoutsTableTable : HtmlTable
    {
        
        public UILayoutsTableTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "layoutsTable";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Introducción a las aplicaciones de Offic";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=\"layoutsTable\" style=\"width: 100%;\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("WorkShop - DevHome");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIIntroducciónalasapliPane
        {
            get
            {
                if ((this.mUIIntroducciónalasapliPane == null))
                {
                    this.mUIIntroducciónalasapliPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIIntroducciónalasapliPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIIntroducciónalasapliPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIIntroducciónalasapliPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Introducción a las aplicaciones de Offic";
                    this.mUIIntroducciónalasapliPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIIntroducciónalasapliPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-rte-layoutszone-inner";
                    this.mUIIntroducciónalasapliPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ms-rte-layoutszone-inner\" style=\"-ms-word-wrap: break-word; min-height: 60" +
                        "px;\"";
                    this.mUIIntroducciónalasapliPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "132";
                    this.mUIIntroducciónalasapliPane.WindowTitles.Add("WorkShop - DevHome");
                    #endregion
                }
                return this.mUIIntroducciónalasapliPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIIntroducciónalasapliPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHomePageMyASPNETApplDocument : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://workshopsceus.azurewebsites.net/?SPHostUrl=https%3A%2F%2Fadriandiaz%2Esha" +
                "repoint%2Ecom%2Fsites%2Fworkshop&SPLanguage=es%2DES&SPClientTag=0&SPProductNumbe" +
                "r=16%2E0%2E4107%2E1222";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://workshopsceus.azurewebsites.net/?SPHostUrl=https%3A%2F%2Fadriandiaz%2Esha" +
                        "repoint%2Ecom%2Fsites%2Fworkshop";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"https://workshopsceus.azurewebsite";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIHomeHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHomePageMyASPNETApplDocument1 : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://workshopsceus.azurewebsites.net/?SPHostUrl=https%3A%2F%2Fadriandiaz%2Esha" +
                "repoint%2Ecom%2Fsites%2Fworkshop";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAboutHyperlink
        {
            get
            {
                if ((this.mUIAboutHyperlink == null))
                {
                    this.mUIAboutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://workshopsceus.azurewebsites.net/Home/About?SPHostUrl=https%3A%2F%2Fadrian" +
                        "diaz%2Esharepoint%2Ecom%2Fsites%2Fworkshop";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"https://workshopsceus.azurewebsite";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIAboutHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIAboutHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAboutHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAboutMyASPNETApplicaDocument : HtmlDocument
    {
        
        public UIAboutMyASPNETApplicaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "About - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/About";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://workshopsceus.azurewebsites.net/Home/About?SPHostUrl=https%3A%2F%2Fadrian" +
                "diaz%2Esharepoint%2Ecom%2Fsites%2Fworkshop";
            this.WindowTitles.Add("About - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContactHyperlink
        {
            get
            {
                if ((this.mUIContactHyperlink == null))
                {
                    this.mUIContactHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://workshopsceus.azurewebsites.net/Home/Contact?SPHostUrl=https%3A%2F%2Fadri" +
                        "andiaz%2Esharepoint%2Ecom%2Fsites%2Fworkshop";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"https://workshopsceus.azurewebsite";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIContactHyperlink.WindowTitles.Add("About - My ASP.NET Application");
                    #endregion
                }
                return this.mUIContactHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContactHyperlink;
        #endregion
    }
}
